name: Build_kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up environment
        run: |
          echo "Install dependencies"
          sudo apt update -y
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev unzip zipalign language-pack-zh-hans
      - name: pull kernel and complier
        run: |
          echo "Pull source-code and compiler"
          git clone --depth=1 https://github.com/donvito007/android_kernel_xiaomi_sdm710-1 -b kernelsu kernel_src  #Change kernel-source path and branch name
          echo "Pull source"
          git clone --depth=1 https://github.com/kdrag0n/proton-clang -b master
          echo "Complete"
      - name: build kernel
        run: |
          echo "Start Compiling Kernel"
          wget https://raw.githubusercontent.com/donvito007/build_kernel/main/build_tool.sh
          chmod +x build_tool.sh
          ./build_tool.sh
      - name : upload 
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: kernel
          path: ${{ github.workspace }}/kernel_src/Image.gz-dtb
#       - name: Release
#         uses: softprops/action-gh-release@v1
#         with:
#           files: ${{ github.workspace }}/kernel_src/Image.gz-dtb

